### PR TITLE
Replace write with combination of mkdir and writeFile

### PR DESCRIPTION
**Pull request by TrySound**
Node v10 introduced a great "recursive" option for mkdir which allows to
get rid from mkdirp package and easily rewrite "write" package usage
with two function calls.

https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback

### CODE REVIEW

**Comment by TrySound** [comment]
cc @royriojas

**Comment by royriojas** [comment]
hi @TrySound very nice!

But can we do this by moving the mkdirp lib to optional dependencies? trying first to use the new method and only in case of failure attempt to use mkdirp, just to keep backwards compatibility?

If not, we would have to consider releasing this as a major upgrade I think, but indeed very nice

**Comment by TrySound** [comment]
I'm not sure optional dependencies can help here. Major bump is safer solution IMO.

**Review by ruyadorno — APPROVED** [review]
@royriojas this PR already proposes dropping support to node4/6/8 which should be a major bump in itself, I'd say go ahead and cut a new semver-major version 👍

**Comment by realityking** [comment]
@royriojas It'd be nice to get a new major version with this change for less dependencies

**Comment by royriojas** [comment]
Will check today which version is using eslint and align. I've been very busy lately but I will try to release a new version without these deps

**Comment by realityking** [comment]
Thank you @royriojas!

**Pull request merged**
