### PR TITLE
FIX: replace circular-json with flatted

### PR DESCRIPTION
**Pull request by Teamop**
Changes
- replace `circular-json` with `flatted`, as `circular-json` has been marked as deprecated, and based on the [READ.ME](https://github.com/WebReflection/circular-json), change to `flatted`
- Add node 8 and 10 to the travis

### CODE REVIEW

**Comment by ai** [comment]
If everyone approved it, can we merge it and release as a patch?

**Comment by royriojas** [comment]
@ai, I believe this will have to be released as minor at least, since we're changing dependencies. Otherwise we will have to let the eslint team know about this been released as a patch, since this package is a dependency in `file-entry-cache` which in time is a dependency in `eslint`, just to avoid causing issues there.

**Comment by platinumazure** [comment]
Hi @royriojas, I'm from the ESLint team.

As long as the functionality of your package is unchanged, you can release as patch or minor if you wish. It would just help us to also have a new release of file-entry-cache with the flat-cache dependency set to use the updated version, so we can solve the deprecation warning on the ESLint side. But definitely no rush on this at all. Thanks!

**Comment by royriojas** [comment]
published as `flat-cache@1.3.1`

Thank you guys!

**Comment by lenovouser** [comment]
@royriojas if I understand you correctly this fix will be released with the next major version?

**Comment by platinumazure** [comment]
I think we need to figure out why the cache structure changed with the upgrade and see if there's a way to avoid that, so that we could publish this as a minor release. I don't think there was an intention to change the cache structure, but it just happened due to the dependency exposing a slightly different API or something.

I'm happy to try to look into that when I have time.

None of this is to speak for @royriojas, who may have a different plan entirely.

**Comment by royriojas** [comment]
@lenovouser yes, it should be on a new major, also we should upgrade the tests in eslint so they don't read the cache directly, because the format is an implementation detail, so it should not be something our tests rely on, I believe.

@platinumazure I'm not having enough spare time these days. But I'm sure the issue is that we should not read the cache directly from eslint tests but to find another way to test.

**Pull request merged**
